name: SwedenSpawners
version: '${project.version}'
main: com.redesweden.swedenspawners.SwedenSpawners
api-version: 1.8.8
authors: [ rachzy ]
description: Plugin original de spawners da Rede Sweden
website: https://rachzy.github.io
depend: [SwedenEconomia, NBTEditor]
softdepend: [DecentHolograms, HeadsPluginAPI]
commands:
  spawners:
    description: Abre o menu de compra de spawners
    usage: /<command>
    aliases:
      - spawner
      - gerador
      - geradores
  limite:
    description: Mostra ao jogador quantos limites este ou outro possui
    usage: /<command> <target>
